- deploy/multi-dc/test/multi-dc-raft.sh
In my [last PR](https://github.com/bank-vaults/vault-operator/pull/18) I forgot to pin the latest stable Bank-Vaults version also in multi-dc test.
> Pin Bank Vaults version in multi-dc test as well

- .github/workflows/ci.yaml
> CI update k8s and vault versions

- charts/vault-operator/crds/crd.yaml
- deploy/cr-awskms.yaml
- deploy/cr-file.yaml
- deploy/cr-gcpkms.yaml
- deploy/cr-init-containers.yaml
- deploy/cr-k8s-startup-secret.yaml
- deploy/cr-oidc.yaml
- deploy/cr-priority.yaml
- deploy/cr-raft.yaml
- deploy/cr.yaml
- deploy/crd.yaml
- pkg/apis/vault/v1alpha1/vault_types.go
Allows users to specify unseal key shares and key threshold based on their specific requirements. The changes in this pull request also include modifications to the Custom Resource Definitions (CRDs), a version bump, and updates to a few example deployment YAML files.
Fixes #56
This pull request introduces a different approach compared to [PR-57](https://github.com/bank-vaults/vault-operator/pull/57), as this is mode independent(not just Kubernetes specific). Users will have the flexibility to utilize the `options` field in `UnsealConfig` to specify their desired values.
Thank you :)
> Allows users to specify unseal key shares and key threshold 

- .github/workflows/ci.yaml
> ci: add magic nix cache

- deploy/dev/multi-dc/aws/multi-dc-raft.sh
- deploy/dev/multi-dc/test/multi-dc-raft.sh
- test/acceptance_test.go
Use bankVaults.image.tag chart value instead of deprecated image.bankVaultsTag (see [here](https://github.com/bank-vaults/vault-operator/blob/bfe2f36aae911f57b04f6dfba4a6b9f36c163fb4/deploy/charts/vault-operator/values.yaml#L27) and [here](https://github.com/bank-vaults/vault-operator/blob/bfe2f36aae911f57b04f6dfba4a6b9f36c163fb4/deploy/charts/vault-operator/README.md?plain=1#L23)).
> chore: use bankVaults.image.tag chart value

- deploy/charts/vault-operator/crds/crd.yaml
- deploy/crd/bases/vault.banzaicloud.com_vaults.yaml
- deploy/examples/cr-aws.yaml
- pkg/apis/vault/v1alpha1/vault_types.go
Features:
This PR is created in order to allow the vault operator to take advantage of [this](https://github.com/banzaicloud/bank-vaults/pull/1968) bank-vaults feature
In our use case, we have an existing vault cluster that has existing unseal keys that are encrypted with a custom encryption context. This feature will allow us to migrate this vault cluster to be managed by bank-vaults.
> feat: Add configurable AWS KMS encryption context

- .licensei.toml
Added busl-1.1 to approved list as this new license is what Hashicorp recently switched to.
> fix(licensei): added busl-1.1 to approved list

- examples/README.md
- examples/base/kustomization.yaml
- examples/base/rbac.yaml
- examples/base/vault.yaml
- examples/file/kustomization.yaml
- examples/file/vault.yaml
- examples/kubernetes-auth/README.md
- examples/kubernetes-auth/kustomization.yaml
- examples/kubernetes-auth/vault.yaml
- examples/startup-secrets/kustomization.yaml
- examples/startup-secrets/vault.yaml
This PR is the first in a row.
It adds new examples that are easier to follow and test.
> Add new examples

- deploy/charts/vault-operator/README.md
- deploy/charts/vault-operator/templates/pdb.yaml
- deploy/charts/vault-operator/values.yaml
Implement pod disruption budget for vault-operator helm-chart
Fixes #323
> feat: Pod disruption budget

- deploy/charts/vault-operator/crds/crd.yaml
- deploy/crd/bases/vault.banzaicloud.com_vaults.yaml
- pkg/apis/vault/v1alpha1/vault_types.go
Previously, the pin had to be provided by the user in their Vault yaml. If you want to keep the pin secret in
source code, then this isn't desirable. Viper defaults to the command line version of the pin, so even if you
set a dummy pin in the yaml and override it via `envsConfig`, bank-vaults won't use the right pin.
This is my first PR here so please check if I missed things that need to be updated.
> fix: make HSM pin an optional argument to allow setting it via the BANK_VAULTS_HSM_PIN env var

- pkg/controller/vault/vault_controller.go
Fixes #366 
This just sets the `jobLabel` in the `ServiceMonitorSpec` to the label name that contains the Vault custom resource name on the Service (which is hard-coded [here](https://github.com/bank-vaults/vault-operator/blob/main/pkg/apis/vault/v1alpha1/vault_types.go#L1024)).
> fix: Use correct label name for ServiceMonitor jobLabel field

- pkg/controller/vault/vault_controller.go
Issue - Vault-Operator fails to create vault-tls secret for new namespaces if any existing namespace is in Terminating State.
Fix -> Skip the namespaces in terminating state.
> fix: Skip CA Secret Upsert for Namespace in Terminating state

- deploy/charts/vault-operator/crds/crd.yaml
- deploy/crd/bases/vault.banzaicloud.com_vaults.yaml
- pkg/apis/vault/v1alpha1/vault_types.go
- pkg/controller/vault/vault_controller.go
This feature allows the operator to use an override for API Scheme (http/https) when calling the Raft leader. If the user does not want to use TLS within Vault, but rather have a reverse proxy and/or load balancer terminate the connection, this override allows `http` or `https` to be added to the `raftLeaderAddress`. By default, this API Scheme is set based upon values provided in the Vault config for TLS. This is non-intrusive and will only override the `raftLeaderAddress` value if provided.
> feat: Add option to allow TLS termination by load balancers

- deploy/rbac/leader_election_role.yaml
With Kubernetes 1.24 and later, short-lived tokens are now a "thing". This change allows the leader-election role to conduct token reviews in line with the advice on [this page](https://developer.hashicorp.com/vault/docs/auth/kubernetes#how-to-work-with-short-lived-kubernetes-tokens)
Without this, you may see errors like this: `cannot create resource "tokenreviews" in API group` (see [this KB article](https://support.hashicorp.com/hc/en-us/articles/8231471929491-Getting-the-error-cannot-create-resource-tokenreviews-in-API-group-during-Kubernetes-Authentication) too)
> fix: Add a tokenreviews role to the leader-election-role

- deploy/charts/vault-operator/templates/_helpers.tpl
Fixes: https://github.com/bank-vaults/vault-operator/issues/526
Added missing `common.capabilities.kubeVersion` and `common.capabilities.policy.apiVersion` template definitions.
> fix(vault-operator helm chart): added missing common.capabilities.kubeVersion and common.capabilities.policy.apiVersion template definitions.

- .github/workflows/ci.yaml
- This PR reduces the CI acceptance-test matrix, to only test againts the latest vault, and supported K8S versions. 
Fixes #135
> feat: reduce test matrix

- deploy/examples/vault-openshift-scc.yaml
Add missing `SETFCAP` capability introduced in https://github.com/bank-vaults/vault-operator/commit/4871a3038dc35b40a5db48bf9bf01826e3f4e9c2 to openshift scc example
> chore: add missing capability to openshift scc example

- deploy/charts/vault-operator/templates/deployment.yaml
- deploy/charts/vault-operator/templates/servicemonitor.yaml
Reverts: 2bd7c7dff7e87376df5db529a66bc725272db409
Fixes: #679
> revert: add instance label to templates

- pkg/controller/vault/vault_controller.go
This PR updates the Vault liveness probe from `/v1/sys/init` to `/sys/health`. The `/v1/sys/init` endpoint does not include health status, which can cause Vault to become inaccessible when its health fails. By aligning the liveness probe with the readiness probe to use `/sys/health`, we ensure consistent behavior and improved reliability.
Additionally, this change aligns with the Vault official Helm chart, which also uses `/sys/health` for both readiness and liveness probes, as specified [here](https://github.com/hashicorp/vault-helm/blob/main/values.yaml#L540).
This change comes in response to an issue where Vault stopped responding due to an unhealthy state. The issue required manually deleting the unhealthy pod to restore functionality. By using `/sys/health`, this problem is mitigated …
> fix: update vault liveness probe to /sys/health for improved reliability

- deploy/charts/vault-operator/templates/deployment.yaml
- deploy/charts/vault-operator/templates/pdb.yaml
- deploy/charts/vault-operator/templates/psp.yaml
- deploy/charts/vault-operator/templates/role.yaml
- deploy/charts/vault-operator/templates/rolebinding.yaml
- deploy/charts/vault-operator/templates/sa.yaml
- deploy/charts/vault-operator/templates/service.yaml
- deploy/charts/vault-operator/templates/servicemonitor.yaml
Add option to deploy resources to Helm release namespace.
Right now all resources are deployed to `default` namespace if not set explicitly with `helm --namespace` flag. This is very confusing. `RBAC `manifests are also tied to `default` namespace but for this i can use `kustomize` or have local copies. For helm chart would be great to stop maintain forked copy.
> feat: add helm release namespace
